language: node_js
node_js:
- '6'
before_install:
- if [ ! -z "$ARTIFACTS_BUCKET" ] && [ ! -z "ARTIFACTS_KEY" ] && [ ! -z "ARTIFACTS_SECRET" ] ; then export UPLOAD_ARTIFACT=yes ; else echo artifact uploading is disabled; fi
install:
  - npm install -g npm@5.3.0 && npm -v
  - npm install --no-optional --no-save --no-update-dependencies
  - if [ ! -z "$UPLOAD_ARTIFACT" ]; then curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash; fi
script:
  - npm run package
after_success:
  - if [ ! -z "$UPLOAD_ARTIFACT" ] ; then artifacts upload --target-paths /${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/NODE-${TRAVIS_NODE_VERSION} dist/app.zip ; fi
  - if [ ! -z "$UPLOAD_ARTIFACT" ] && [ ! -z "$TRAVIS_PULL_REQUEST_SLUG" ] ; then npm run dpat -- travis pr-comment . --s3target /${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/NODE-${TRAVIS_NODE_VERSION}; fi
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mgoWsyI37oHzqdtT4RjjaLtAQDF8qQa8B1Ron0Il5S4jEObqzNrMwFH4KajKFZw/bddlLyMD8GUXAz9+e/JiFttdRcZl9i8oZhB/gEsoWMrLlWsIzRfpMwV22H1CeqXuvwcIpE+RDIHkSQn4VaGqMJGfREPvDDQRpfA4LrtrkXHfOGi+LWQojimR4Lf/fjmy+fcXqol5jXKIF8K8HmklubXx/OwtC6HoxRHA1kM4hdUXvgbevqDkS5LM1mTslH4AuXoU3u9Qd8ps8fcBGGWVynjOg8edxVMYjJEzMDdA9azqcSvWTf4lhkikWpDY2qXNfd1Vh7yX2Roa/ZECRXRBkxB7I1ea1IrdfM5CzWsg4BahzwQSm3z/roDIZQ4KT/dgrUSjKB6+rKYpzDNs2qHYPtKuFcHsg5Efi7rmatmemXFm71urcMU5nbhWikYRGb+tlrbTmkcq7nrjMMprYeVAtL6AoqIAjoltYCuKUjrE4HT1/9mP4BQ/c2tODGZ915QLe+9ykQpzjLWx3D2uAEa7lIMWc+WL8ByxJYWLYfm67vcnCEYeMcN9PKht0RTPAB53kXLQ+FodF2t9m4+hcCM4mQFQA4qJl8fgw0ITtVQztsoop/bSGRdN6Qaf6DuquCvru6CDYvxFJAFCj8VzMzfXbOfwNG4BuKFgZGzJgEqw8/s=
  file: dist/app.zip
  on:
    tags: true
